vich_uploader:
    db_driver: orm

    mappings:
        dishPhoto:
            uri_prefix: /images/dish
            upload_destination: '%kernel.project_dir%/public/images/dish'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer